mybatis:
  typeAliasesPackage: com.stlife.data.db.mybatis.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: cloud
    driver-class-name: com.mysql.jdbc.Driver